# Generated by Django 5.2.7 on 2025-10-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_profile_options_bankcredentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcredentials',
            name='login',
            field=models.CharField(blank=True, max_length=255, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='bankcredentials',
            name='password',
            field=models.CharField(blank=True, max_length=255, verbose_name='Пароль'),
        ),
    ]
