# Generated by Django 5.2.7 on 2025-10-30 18:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_connect_statis_bankcredentials_connect_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankcredentials',
            options={'verbose_name': 'Банковские реквизиты', 'verbose_name_plural': 'Банковые реквизиты'},
        ),
        migrations.RemoveField(
            model_name='bankcredentials',
            name='connect_status',
        ),
        migrations.AddField(
            model_name='bankcredentials',
            name='account_cons',
            field=models.CharField(blank=True, max_length=255, verbose_name='Согласие на получение данных'),
        ),
        migrations.AddField(
            model_name='bankcredentials',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='bankcredentials',
            name='bank_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='Банк токен'),
        ),
        migrations.AddField(
            model_name='bankcredentials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankcredentials',
            name='status_cons',
            field=models.BooleanField(default=False, verbose_name='Статус согласия'),
        ),
        migrations.AddField(
            model_name='bankcredentials',
            name='status_token',
            field=models.BooleanField(default=False, verbose_name='Статус токена'),
        ),
        migrations.AddField(
            model_name='bankcredentials',
            name='team',
            field=models.CharField(blank=True, max_length=255, verbose_name='Команда'),
        ),
        migrations.AddField(
            model_name='bankcredentials',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
    ]
