# Generated by Django 5.2.7 on 2025-10-31 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='login',
            new_name='team_login',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='password',
            new_name='team_password',
        ),
    ]
