# Generated by Django 5.2.7 on 2025-10-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_bankcredentials_login_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankcredentials',
            options={'verbose_name': 'Банковые реквизиты', 'verbose_name_plural': 'Банковые реквизиты'},
        ),
        migrations.AddField(
            model_name='bankcredentials',
            name='connect_statis',
            field=models.BooleanField(default=False),
        ),
    ]
