# Generated by Django 5.2.7 on 2025-10-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_bankcredentials_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankcredentials',
            old_name='connect_statis',
            new_name='connect_status',
        ),
    ]
