# Generated by Django 5.2.7 on 2025-10-30 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_bankcredentials_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankCredentials',
        ),
    ]
