# Generated by Django 5.2.7 on 2025-10-30 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_delete_bankcredentials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('ALFA', 'ALFA'), ('VTB', 'VTB'), ('SBER', 'SBER')], max_length=20, verbose_name='Банк')),
                ('team', models.CharField(max_length=255, verbose_name='Team')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('bank_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен банка')),
                ('bank_token_status', models.BooleanField(default=False, verbose_name='Статус токена')),
                ('account_consents', models.CharField(blank=True, max_length=255, null=True, verbose_name='Разрешения по счёту')),
                ('account_consents_status', models.BooleanField(default=False, verbose_name='Статус разрешений')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Банк пользователя',
                'verbose_name_plural': 'Банки пользователя',
                'unique_together': {('user', 'bank_name')},
            },
        ),
    ]
