# Generated by Django 5.2.7 on 2025-11-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_rename_login_bank_team_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_consents_status',
            field=models.CharField(choices=[('NONE', 'Нет'), ('PENDING', 'Ожидает подтверждения'), ('ACTIVE', 'Работает')], default='NONE', max_length=10, verbose_name='Статус разрешения на доступ'),
        ),
    ]
